apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kubernetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kubernetes-app
  template:
    metadata:
      labels:
        app: test-kubernetes-app
    spec:
      containers:
      - name: test-kubernetes-app
        image: test-kubernetes-app
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080