apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s-v2
  namespace: dev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-k8s-v2
  template:
    metadata:
      labels:
        app: app-k8s-v2
    spec:
      containers:
      - name: app-k8s-v2
        image: app-k8s-v2
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi" # Aumenta la memoria
            cpu: "500m"
          requests:
            memory: "256Mi"  # Aumenta la memoria solicitada
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URI