apiVersion: v1
kind: Service
metadata:
  name: app-k8s-v2-service
  namespace: dev-app
spec:
  type: NodePort
  ports:
    - port: 80 # Port exposed from the service
      targetPort: 8080 # Port where the container listens
      nodePort: 30007 # Port of the node that will be accessible from your local machine
  selector:
    app: app-k8s-v2