apiVersion: v1
kind: Service
metadata:
  name: test-kubernetes-app-service
spec:
  type: NodePort
  selector:
    app: test-kubernetes-app
  ports:
  - protocol: TCP
    port: 80 # Puerto expuesto del servicio
    targetPort: 8080 # Puerto donde escucha el contenedor
    nodePort: 30007 # Puerto del nodo que será accesible desde tu máquina local