apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s-v2
  namespace: dev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-k8s-v2
  template:
    metadata:
      labels:
        app: app-k8s-v2
    spec:
      containers:
      - name: app-k8s-v2
        image: app-k8s-v2
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90  # Time to wait before the probe begins
          periodSeconds: 20 # How many seconds should you check
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60   # Time to wait before the probe begins
          periodSeconds: 10 # How many seconds should you check
          timeoutSeconds: 10
          failureThreshold: 5
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URI