apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-k8s-v2-hpa
  namespace: dev-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-k8s-v2
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Escalar cuando el uso promedio de CPU supere el 50%
